server {
    listen 80;
    server_name _;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Tenta carregar o URI solicitado. Se não encontrar, redireciona pro index.html
        # Fundamental para roteamento client-side (SPA) funcionar quando usar links diretos
        try_files $uri $uri/ /index.html;
    }

    # Opcional: caches eficientes para assets estáticos
    location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico|woff|woff2|ttf|eot)$ {
        root /usr/share/nginx/html;
        expires max;
        log_not_found off;
    }
}
